# Generated by Django 3.2 on 2021-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit',
            field=models.IntegerField(verbose_name='Deposit (euro)'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='rate',
            field=models.FloatField(verbose_name='Rate (decimal'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='term',
            field=models.IntegerField(verbose_name='Term (years)'),
        ),
    ]
